"use client";
import { useEffect,useState } from "react";
import { Button,Card,Heading,Text } from "@/components/ui";
import type { ConsultationPublicRequest } from "@/types/member-consultation";

type Snapshot={quota:{total:number;available:number;reserved:number;consumed:number};requests:ConsultationPublicRequest[]};
const DEFAULT_LINES=[7,8,7,8,7,8] as number[];
export function MemberConsultationClient(){
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [kind,setKind]=useState<"LIUYAO"|"BAZI">("LIUYAO");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [supplementId,setSupplementId]=useState<string|null>(null);const [answers,setAnswers]=useState<Record<string,{content:string;disclosure:string}>>({});
  async function refresh(){const r=await fetch("/api/member/consultations",{cache:"no-store"});const j=await r.json();if(r.ok)setSnapshot(j);else setMessage(j.error??"咨询服务暂不可用");}
  useEffect(()=>{void refresh();},[]);
  async function submit(form:FormData){setBusy(true);setMessage("");const common={kind,timezone:String(form.get("timezone")),location:String(form.get("location")),horizon:String(form.get("horizon")),consent:form.get("consent")==="on"};const payload=kind==="LIUYAO"?{...common,question:String(form.get("question")),scope:String(form.get("scope")),castAt:String(form.get("castAt")),castMethod:String(form.get("castMethod")),linesBottomUp:DEFAULT_LINES.map((_,i)=>Number(form.get(`line${i}`)))}:{...common,calendarType:String(form.get("calendarType")),leapMonth:form.get("leapMonth")==="on",birthDate:String(form.get("birthDate")),birthTime:form.get("birthTime")?String(form.get("birthTime")):null,timePrecision:String(form.get("timePrecision")),sourceConfidence:String(form.get("sourceConfidence")),trueSolarTimeConsent:form.get("trueSolarTimeConsent")==="on",topic:String(form.get("topic")),gender:"UNSPECIFIED"};const r=await fetch(supplementId?`/api/member/consultations/${supplementId}`:"/api/member/consultations",{method:supplementId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setMessage(r.ok?(supplementId?"补充资料已提交，不会再次扣减权益。":"申请已提交，等待易老师复核。"):`提交失败：${j.error??"UNKNOWN"}`);if(r.ok){setSupplementId(null);await refresh();}setBusy(false);}
  return <div className="space-y-5">
    <div><Heading as="h1" size="h2">会员六爻 / 八字咨询</Heading><Text variant="body-sm" color="secondary" className="mt-2 block">月度1次、季度3次、年度12次。AI仅辅助整理草稿；未经易老师本人批准不会交付。</Text></div>
    <Card padding="md"><Text variant="body" weight="semibold">权益余额</Text><Text variant="body-sm" className="mt-2 block">可用 {snapshot?.quota.available??"—"} · 审核中 {snapshot?.quota.reserved??"—"} · 已使用 {snapshot?.quota.consumed??"—"}</Text></Card>
    <Card padding="lg"><div className="flex gap-2"><Button type="button" variant={kind==="LIUYAO"?"primary":"outline"} onClick={()=>setKind("LIUYAO")}>六爻</Button><Button type="button" variant={kind==="BAZI"?"primary":"outline"} onClick={()=>setKind("BAZI")}>八字</Button></div>
      <form action={submit} className="mt-5 grid gap-3"><input name="timezone" required placeholder="IANA时区，例如 Asia/Hong_Kong" className="rounded-md border bg-transparent p-3"/><input name="location" required placeholder="地点" className="rounded-md border bg-transparent p-3"/><input name="horizon" required placeholder="问题时间范围" className="rounded-md border bg-transparent p-3"/>
      {kind==="LIUYAO"?<><textarea name="question" required placeholder="一个明确问题" className="rounded-md border bg-transparent p-3"/><input name="scope" required placeholder="问题边界" className="rounded-md border bg-transparent p-3"/><input name="castAt" type="datetime-local" required className="rounded-md border bg-transparent p-3"/><input name="castMethod" required placeholder="起卦方法" className="rounded-md border bg-transparent p-3"/><div className="grid grid-cols-3 gap-2">{DEFAULT_LINES.map((n,i)=><select key={i} name={`line${i}`} defaultValue={n} className="rounded-md border bg-background p-3" aria-label={`第${i+1}爻（自下而上）`}>{[6,7,8,9].map(v=><option key={v}>{v}</option>)}</select>)}</div></>:<><select name="calendarType" className="rounded-md border bg-background p-3"><option value="GREGORIAN">公历</option><option value="LUNAR">农历</option></select><label><input type="checkbox" name="leapMonth"/> 闰月</label><input type="date" name="birthDate" required className="rounded-md border bg-transparent p-3"/><select name="timePrecision" className="rounded-md border bg-background p-3"><option value="EXACT">时间准确</option><option value="UNKNOWN">时间未知</option></select><input type="time" name="birthTime" className="rounded-md border bg-transparent p-3"/><select name="sourceConfidence" className="rounded-md border bg-background p-3"><option value="HIGH">来源高置信</option><option value="MEDIUM">来源中等</option><option value="LOW">来源待核</option></select><input name="topic" required placeholder="咨询主题" className="rounded-md border bg-transparent p-3"/><label><input type="checkbox" name="trueSolarTimeConsent" required/> 同意校正真太阳时；未确认命盘前不推造四柱或大运</label></>}
      <label><input type="checkbox" name="consent" required/> 同意加密保存本次资料并由MOOX研究系统辅助处理，最终由易老师本人复核</label><Button disabled={busy||(!supplementId&&snapshot?.quota.available===0)}>{busy?"提交中…":supplementId?"提交补充资料（不重复扣减）":"提交并预留1次权益"}</Button></form>{message?<Text variant="body-sm" className="mt-3 block">{message}</Text>:null}</Card>
    <section><Heading as="h2" size="h3">我的申请</Heading><div className="mt-3 space-y-3">{snapshot?.requests.map(r=>{const answer=answers[r.id];return <Card key={r.id} padding="md"><Text variant="body-sm" weight="semibold">{r.kind} · {r.status}</Text><Text variant="caption" color="secondary" className="mt-1 block">{r.reviewerLabel}</Text>{r.missingFields.length?<Text variant="caption" className="mt-1 block">需补充：{r.missingFields.join("、")}</Text>:null}{answer?<><Text variant="body-sm" className="mt-3 block whitespace-pre-wrap">{answer.content}</Text><Text variant="caption" color="tertiary" className="mt-2 block">{answer.disclosure}</Text></>:null}<div className="mt-3 flex gap-2">{r.status==="APPROVED"&&!answer?<Button size="sm" variant="outline" onClick={async()=>{const response=await fetch(`/api/member/consultations/${r.id}`,{cache:"no-store"});const json=await response.json();if(response.ok)setAnswers(current=>({...current,[r.id]:{content:json.content,disclosure:json.disclosure}}));else setMessage("答复读取或访问审计失败，请稍后重试。");}}>查看已复核答复</Button>:null}{r.status==="NEEDS_INFO"?<Button size="sm" variant="outline" onClick={()=>{setKind(r.kind);setSupplementId(r.id);window.scrollTo({top:0,behavior:"smooth"});}}>补充同一申请</Button>:null}{["APPROVED","REJECTED","CANCELLED","SYSTEM_FAILED","INFO_EXPIRED"].includes(r.status)?<Button size="sm" variant="outline" onClick={async()=>{if(!window.confirm("删除加密私密资料和答复？最小权益审计记录仍会保留。"))return;await fetch(`/api/member/consultations/${r.id}?purge=1`,{method:"DELETE"});await refresh();}}>删除私密资料</Button>:null}</div></Card>;})}</div></section>
  </div>;
}
