import "server-only";
import Link from "next/link";
import { XU_REVIEW_DAYS, XU_REVIEW_VERSION, XU_OFFICIAL_REFERENCES, xuReviewContext } from "@/lib/research/us-equity-xu-review-20260925.server";

/** Render only after the member/device page gate. No client bundle or trading integration. */
export function UsEquityXuReview({ en = false, compact = false, nowMs }: { en?: boolean; compact?: boolean; nowMs: number }) {
  const context = xuReviewContext(nowMs);
  const text = (zh: string, english: string) => en ? english : zh;
  const prefix = en ? "/en" : "";
  const archive = context.phase === "archive";
  return <section id="us-equity-xu-20260925" data-us-equity-review={XU_REVIEW_VERSION} className="mx-auto my-6 w-full max-w-7xl rounded-2xl border border-amber-300/25 bg-slate-950 p-5 text-slate-100 sm:p-7">
    <p className="text-xs uppercase tracking-wider text-amber-200">{text("会员研究修订 · 2026-09-25 · V1", "Member research edition · 2026-09-25 · V1")}</p>
    <h2 className="mt-2 text-xl font-semibold sm:text-2xl">{archive ? text("历史存档：", "Archived: ") : ""}{text("美股：以震荡下跌为基准，保留反弹与方向分歧", "US equities: a choppy-down baseline, with rebounds and dissent retained")}</h2>
    <p className="mt-3 text-sm leading-7 text-slate-300">{text("适用窗口：2026年10月8日至11月6日（戌月，不等于公历10月）。易老师本次基准为“震荡下跌”：反弹若不过阶段高点、低点继续下移，才强化偏空判断；不是每天必跌，也不是三方一致看空。", "Coverage: Oct 8–Nov 6, 2026 (the Xu cycle, not calendar October). Yi’s baseline is a choppy decline: failed rallies and lower lows would strengthen it. This does not mean every session falls or that all sources agree.")}</p>
    <p className="mt-3 rounded-lg border border-amber-300/20 bg-amber-300/5 p-3 text-sm leading-6 text-amber-100">{context.phase === "upcoming"
      ? text("本窗口尚未开始。9/25–10/7 没有这批材料对应的逐日授权，不用10月日期补写9月走势。", "This window has not started. These sources do not authorize daily calls for Sep 25–Oct 7; October dates are not backfilled into September.")
      : archive ? text("本版本已到期，只用于复盘；不自动延长预测，也未自动核验命中率。", "This edition has expired and is retained for review only. No automatic extension or hit-rate claim.")
      : context.today ? `${text("美国交易日期观察：", "US session-date watch: ")}${context.date} · SPY ${en ? context.today.spy.en : context.today.spy.zh} · QQQ ${en ? context.today.qqq.en : context.today.qqq.zh}`
      : text("当前纽约日期为周末，无正常股票交易日预测；参考后续窗口，不自动顺延原判断。", "The current New York date is a weekend. No regular equity-session call; source calls are not automatically rolled forward.")}</p>
    <p className="mt-3 text-xs leading-6 text-slate-400">{text("独立研究版本，不覆盖已锁定正式日/月预测，不接入自动交易。未评估概率、胜率或共识星级；目前没有足够的 SPY/QQQ 当期技术点位，不编造入场、止损或目标。", "Independent research, not a replacement for locked daily/monthly forecasts or an automated order signal. Probability, hit rate and consensus stars are unassessed. Current SPY/QQQ entry, stop and target levels are not fabricated.")}</p>
    <p className="mt-1 text-xs leading-6 text-slate-400">{text("SPY、QQQ 是分别观察标普500、纳指100的ETF，不等于SPX、NDX指数报价；本版不新增或更改指数锁定预测。", "SPY and QQQ are ETF proxies for the S&P 500 and Nasdaq-100, not SPX/NDX index quotes. This edition does not create or change locked index forecasts.")}</p>
    {compact ? <Link prefetch={false} className="mt-4 inline-block text-sm text-sky-300 underline underline-offset-4" href={`${prefix}/member/monthly#us-equity-xu-20260925`}>{text("查看月度分歧、22个交易日与失效条件 →", "Read the monthly dissent, 22-session calendar and invalidation →")}</Link> : <>
      <div className="mt-5 grid gap-3 lg:grid-cols-3">
        <article className="rounded-xl border border-rose-300/20 p-4"><h3 className="font-semibold text-rose-200">{text("易老师｜研究基准：震荡下跌", "Yi | Research baseline: choppy decline")}</h3><p className="mt-2 text-sm leading-7 text-slate-300">{text("总体重心下移，中间允许明显反弹。弱势确认要看反弹不过前高、支撑失守与市场宽度转弱；关键日只提高观察优先级，不直接决定方向。", "A downward drift can include substantial rebounds. Watch for failed highs, broken support and weakening breadth. Timing windows prioritize observation; they do not determine direction.")}</p></article>
        <article className="rounded-xl border border-emerald-300/20 p-4"><h3 className="font-semibold text-emerald-200">{text("狼叔｜SPY 月度原判断：震荡偏涨", "Wolf | Original SPY monthly bias: choppy upside")}</h3><p className="mt-2 text-sm leading-7 text-slate-300">{text("月度框架保留10/23–27主要上涨窗口；周级路径包含26–27前段先跌、随后反弹，两者不强行合并。若23日后持续下跌，应降低原偏涨路径可信度。QQQ仅收到周级对照，未补造完整月卦。", "The monthly framework retains an Oct 23–27 advance window; the weekly path first weakens on Oct 26–early 27, then rebounds. Both scopes remain visible. Continued losses after the 23rd would challenge the bullish path. QQQ has a weekly comparison, not a supplied complete monthly reading.")}</p></article>
        <article className="rounded-xl border border-sky-300/20 p-4"><h3 className="font-semibold text-sky-200">{text("Stone 宏观稿｜条件性风险", "Stone macro text | Conditional risk")}</h3><p className="mt-2 text-sm leading-7 text-slate-300">{text("按用户提供的9/24宏观稿归纳：长端利率继续走高可能增加估值压力；若收益率回落且股价保持强势，偏空依据减弱。作者未给10月整月必跌或SPY/QQQ逐日方向；“下周10Y到5.5%”是压力设想，不是现价或必然崩盘线。", "From the user-supplied Sep 24 macro text: rising long yields may pressure valuations; falling yields alongside resilient equities weaken the bearish case. It does not establish a full-month decline or daily ETF calls. A 5.5% 10-year yield next week is the author’s stress scenario, not an observed quote or crash threshold.")}</p></article>
      </div>
      <div className="mt-5 rounded-xl border border-white/10 p-4 text-sm leading-7 text-slate-300">
        <h3 className="font-semibold text-white">{text("综合路径与可证伪条件", "Synthesis and falsifiable conditions")}</h3>
        <p className="mt-2">{text("路径假设：前段反复与分化 → 10/20–23重点观察回落 → 23日后修复、26–27再探 → 27–29反弹 → 月末兑现 → 11月初先弱后修复再转弱。它是用户偏空基准叠加原文窗口的情景，不是精确价格轨迹。", "Working path: early chop and divergence → pullback watch around Oct 20–23 → repair, then another test on 26–27 → rebound on 27–29 → month-end fading → early-November weakness, repair and renewed risk. This combines the user baseline with source windows, not a precise price trajectory.")}</p>
        <p className="mt-2 text-emerald-200">{text("偏空减弱/失效：SPY、QQQ突破阶段反弹高点并回踩守住，持续形成更高高点和低点，尤其伴随收益率回落与上涨家数扩散。此时不能仍把上涨一概叫作“下跌前的反弹”。没有明确价格确认，也不能靠MACD死叉或一个日期断言趋势反转。", "Bearish weakening/invalidation: SPY and QQQ reclaim and hold their stage highs, then sustain higher highs/lows, especially with falling yields and broader participation. Persistent strength cannot always be dismissed as a pre-decline bounce. A MACD crossover or date alone does not establish a reversal.")}</p>
      </div>
      <details open className="mt-5 rounded-xl border border-white/10 p-4">
        <summary className="cursor-pointer font-semibold">{text("逐交易日观察日历 · SPY / QQQ · 22天", "Session-by-session watch calendar · SPY / QQQ · 22 days")}</summary>
        <p className="mt-3 text-xs leading-6 text-slate-400">{text("以下是所给周级对照的摘要映射，非独立日卦、非收盘涨跌承诺。日期暂按美国股票交易日期编排，原文盘中时区待核验，不换算成北京时间下单点；美国交易日晚间对应北京时间当晚至次日。10/24–25、10/31–11/1休市，10/12美股开市。", "These rows summarize supplied weekly windows, not independent daily readings or promised closing returns. Dates are provisionally US equity session labels; intraday source timezone is unverified, so no Beijing-time order triggers are inferred. US sessions span evening to the following morning in Beijing. Oct 24–25 and Oct 31–Nov 1 are weekends; Oct 12 is open.")}</p>
        <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><caption className="sr-only">{text("戌月美股条件研究日历", "Xu-cycle US equity conditional research calendar")}</caption><thead><tr className="border-b border-white/15"><th scope="col" className="p-2">{text("日期", "Date")}</th><th scope="col" className="p-2">SPY</th><th scope="col" className="p-2">QQQ</th><th scope="col" className="p-2">{text("确认与分歧", "Conditions / dissent")}</th></tr></thead><tbody>{XU_REVIEW_DAYS.map(row => <tr key={row.date} className={`border-b border-white/10 align-top ${context.phase === "active" && row.date === context.date ? "bg-amber-300/10" : ""}`}><th scope="row" className="whitespace-nowrap p-2 font-mono text-xs">{row.date.slice(5)}</th><td className="p-2 leading-6">{en ? row.spy.en : row.spy.zh}</td><td className="p-2 leading-6">{en ? row.qqq.en : row.qqq.zh}</td><td className="p-2 text-xs leading-6 text-slate-400">{row.caution ? en ? row.caution.en : row.caution.zh : text("观察结构确认；不按日期机械交易", "Confirm the structure; no mechanical date-based trade")}</td></tr>)}</tbody></table></div>
      </details>
      <details className="mt-4 rounded-xl border border-white/10 p-4 text-sm leading-7 text-slate-300"><summary className="cursor-pointer font-semibold text-white">{text("依据、版本与缺口", "Evidence, version and gaps")}</summary>
        <p className="mt-3">{text("来源：用户9/25基准、所给狼叔SPY/QQQ戌月图文与9/24宏观转录；只发布研究摘要，不转载全套付费原文。版本原因：补充新材料及方向分歧，不把旧预测改成事后正确。原文月/周窗口不同、转录部分高低点冲突，优先并列图表周期，不擅自宣布某版被替代。原油材料只用于宏观背景，绝不把原油关键日搬到美股。", "Sources: the user’s Sep 25 baseline, supplied Wolf SPY/QQQ Xu-cycle materials and Sep 24 macro transcript. Research summaries only, not a reproduction of paid reports. This edition adds evidence and dissent; it does not retrospectively repair old forecasts. Monthly/weekly paths and transcript turning-point conflicts remain separate. Oil timing is not transferred to equity calls.")}</p>
        <p className="mt-2">{text("9/24美国财政部日值：10Y 5.18%、30Y 5.47%，是带日期的背景，不是实时行情。原文“日元当天到160”与日银东京时段数据不一致，未作已核实事实。FOMC 10/27–28、就业报告11/6仅作为事件风险，不能预定涨跌。", "Sep 24 Treasury daily observations: 10Y 5.18%, 30Y 5.47%; dated context, not live quotes. The transcript’s USD/JPY 160 claim conflicts with BOJ Tokyo-session data and is not treated as verified. The Oct 27–28 FOMC and Nov 6 jobs report are event risks, not directional guarantees.")}</p>
        <div className="mt-3 flex flex-wrap gap-x-5 gap-y-2">{XU_OFFICIAL_REFERENCES.map(source => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="text-sky-300 underline underline-offset-4">{source.label}</a>)}</div>
      </details>
    </>}
  </section>;
}
