import type { MethodologyConfig, MethodologyModule } from "@/lib/methodology/types";

/** Built-in defaults — 六爻 is the core pillar. */
export const DEFAULT_METHODOLOGY_MODULES: MethodologyModule[] = [
  {
    id: "liuyao",
    enabled: true,
    publicDisplay: true,
    nameZh: "六爻",
    nameEn: "Liu Yao (I Ching)",
    summaryZh:
      "核心主判断：用于判断市场主方向、阶段节奏与路径特征。六爻是综合体系中最重要的研究输入，不是确定性结论，也不构成必然涨跌承诺。",
    summaryEn:
      "Core judgment for primary direction and path. Liu Yao is the primary research input within the composite system — not deterministic prediction.",
    weightRangeZh: "核心（主判断）",
    weightRangeEn: "Core (primary)",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "qimen",
    enabled: true,
    publicDisplay: true,
    nameZh: "奇门遁甲",
    nameEn: "Qimen Dunjia",
    summaryZh: "时间窗口：拆解周内节奏与关键时点，不独立翻转已经锁定的周卦方向。",
    summaryEn: "Timing windows and rhythm only; it never flips a locked weekly direction by itself.",
    weightRangeZh: "高",
    weightRangeEn: "High",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "market_structure",
    enabled: true,
    publicDisplay: true,
    nameZh: "技术分析",
    nameEn: "Technical Analysis",
    summaryZh: "缠论与技术执行层：负责结构完成、支撑、压力、入场、止损和盈亏比；不能独立改方向，但可在发布前参与两份冲突六爻的交叉验证。",
    summaryEn: "Chan and technical execution cover structure, levels, entries, stops and risk/reward. They cannot change direction alone, but may help arbitrate conflicting Liu Yao candidates before publication.",
    weightRangeZh: "点位工具／预发布交叉验证",
    weightRangeEn: "Levels / pre-publication cross-check",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "macro_flows",
    enabled: true,
    publicDisplay: true,
    nameZh: "消息面",
    nameEn: "News & Catalysts",
    summaryZh: "信息与风险校验：事件、政策、资金偏好和扰动因素只影响执行质量、仓位和等待，不覆盖正式方向。",
    summaryEn: "Events, policy, flows and disruptions affect execution quality and risk, not the locked direction.",
    weightRangeZh: "中高",
    weightRangeEn: "Medium-high",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "wave",
    enabled: true,
    publicDisplay: true,
    nameZh: "波浪分析",
    nameEn: "Wave Analysis",
    summaryZh: "辅助观察：接近波浪关键位时权重可临时提高，不构成预测主体。",
    summaryEn: "Supporting observation; weight may rise near key wave levels.",
    weightRangeZh: "辅助",
    weightRangeEn: "Auxiliary",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "ai_quant",
    enabled: true,
    publicDisplay: true,
    nameZh: "AI／量化",
    nameEn: "AI & Quant",
    summaryZh: "信息过滤与纪律执行：可提醒、降仓、延迟或否决一笔交易，但不能修改已锁定方向。",
    summaryEn: "Information and execution discipline: may alert, resize, delay or block a trade, but cannot edit the locked direction.",
    weightRangeZh: "辅助",
    weightRangeEn: "Auxiliary",
    updatedAt: "2026-07-29T00:00:00+08:00",
  },
  {
    id: "cycle",
    enabled: true,
    publicDisplay: true,
    nameZh: "周期分析",
    nameEn: "Cycle Analysis",
    summaryZh: "大周期背景：用于判断上涨、下跌或震荡环境，以及本周是顺势还是逆势修正；不替代当前周卦。",
    summaryEn: "Higher-horizon context for regime and trend alignment; it does not replace the active weekly reading.",
    weightRangeZh: "辅助（约15%）",
    weightRangeEn: "Auxiliary (~15%)",
    updatedAt: "2026-07-31T20:00:00+08:00",
  },
  {
    id: "bazi",
    enabled: true,
    publicDisplay: true,
    nameZh: "八字背景",
    nameEn: "BaZi Background",
    summaryZh: "用于长期行业、资产与关键人物背景。关键人物八字必须先核验出生资料并做历史事件回验，只作用于月度以上旁证，不覆盖资产自身卦象。",
    summaryEn: "Long-horizon context for assets and tightly linked key people. Birth data and historical backtesting are required; it never overrides the asset reading.",
    weightRangeZh: "中长期旁证（默认5%，最高10%）",
    weightRangeEn: "Long-horizon corroboration (5%, max 10%)",
    updatedAt: "2026-07-31T20:00:00+08:00",
  },
  {
    id: "analyst",
    enabled: true,
    publicDisplay: true,
    nameZh: "分析师情报",
    nameEn: "Analyst Intelligence",
    summaryZh: "汇总有明确发布时间与有效窗口的外部观点，采用低至中等权重并按时间衰减。",
    summaryEn: "External research weighted by verified history.",
    weightRangeZh: "辅助（动态）",
    weightRangeEn: "Auxiliary (dynamic)",
    updatedAt: "2026-07-31T20:00:00+08:00",
  },
];

export function defaultMethodologyConfig(): MethodologyConfig {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    modules: DEFAULT_METHODOLOGY_MODULES.map((m) => ({ ...m })),
  };
}
