import type { Metadata } from "next";
import Link from "next/link";
import { unstable_noStore as noStore } from "next/cache";
import { Badge, Heading, Section, Text } from "@/components/ui";
import { PublicFeaturePreview } from "@/components/access/PublicFeaturePreview";
import { MemberDeviceGate } from "@/components/access/MemberDeviceGate";
import { MemberDeviceHeartbeat } from "@/components/access/MemberDeviceHeartbeat";
import { MemberStockResearchDashboard } from "@/components/conviction/MemberStockResearchDashboard";
import { getMemberDevicePageAccess } from "@/lib/auth/member-device-guard";
import { getConvictionListPagePayload } from "@/lib/data/conviction/access";
import { buildLocalizedPageMetadata, getRequestLocale } from "@/lib/i18n/server";

export const dynamic = "force-dynamic"; export const revalidate = 0; const path = "/member/stock-picks";
export async function generateMetadata(): Promise<Metadata> { const locale = await getRequestLocale(); return buildLocalizedPageMetadata({ locale, basePath: path, titleZh: "会员股票研究 | MOOX", titleEn: "Member Stock Research | MOOX", descriptionZh: "从整月路线、当前阶段、本周六爻到日内奇门与缠论交叉验证。", descriptionEn: "Member stock research from monthly path and current stage to weekly Liu Yao and daily cross-checks." }); }
export default async function MemberStockPicksPage(){noStore();const gate=await getMemberDevicePageAccess();if(gate.status==="LOGIN_REQUIRED"||gate.status==="MEMBERSHIP_REQUIRED"){const en=(await getRequestLocale())==="en";return <main><Section spacing="lg"><PublicFeaturePreview eyebrow={en?"Stock research · Public preview":"股票研究 · 公开预览"} title={en?"Read the monthly path before the weekly trade":"先看整月路线，再看本周阶段"} description={en?"Each asset aligns its monthly path, current stage, weekly route, projected candles and daily technical confirmation. Missing evidence remains blank instead of being invented.":"每个标的按整月路线、当前阶段、本周路径、模拟K线和日内技术确认排列；证据不足就留空。"} solves={en?["Locate the current stage","Compare monthly and weekly direction","Separate forecast candles from actual prices"]:["判断当前走到哪一段","对照月线与周线是否同向","区分预测K线与实际价格"]} memberBenefits={en?["Monthly and weekly route","Projected candles with date and price axes","4H structure and invalidation","Preserved verification history"]:["月度与周度路线","带日期和价格轴的模拟K线","4H结构与失效条件","保留历史验证结果"]} exampleTitle={en?"Stock research card":"股票研究卡"} exampleLines={en?["Monthly: rally then fade","Current stage: early rally","Weekly: range-up","Daily: wait for 4H confirmation"]:["整月：先涨后跌","当前：上行前段","本周：震荡上涨","日内：等待4H确认"]} nextPath={path}/></Section></main>}if(gate.status==="DEVICE_REQUIRED")return <main><Section spacing="lg"><MemberDeviceGate decision={gate.device} nextPath={path}/></Section></main>;const payload=await getConvictionListPagePayload();return <><MemberDeviceHeartbeat/><main className="min-h-screen bg-[#07080a] text-white"><Section spacing="lg"><div className="mx-auto w-full max-w-[1240px]"><Badge variant="default">会员专享</Badge><Heading as="h1" size="h2" className="mt-4 text-white">股票研究 · 月周日路线</Heading><Text variant="body" className="mt-3 block max-w-4xl text-white/58">先看整月方向与当前阶段，再看本周主走势；日分析并列周内节奏、奇门和4H缠论，缺少证据直接留空。</Text><Link href="/member/sector-resonance" className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.04] px-5 py-4 text-sm text-cyan-100/75 transition hover:border-cyan-300/30 hover:bg-cyan-300/[.07]"><span><b className="text-white">查看板块共振分析</b><span className="ml-2 text-white/42">本周、下周及9月各周全部重点资产对照</span></span><span>进入 →</span></Link><div className="mt-7"><MemberStockResearchDashboard rows={payload.stockResearchRows ?? []}/></div></div></Section></main></>}
