import type { AiTradingDeskSnapshot } from "@/types/ai-trading-desk";

export function createMemberAiTradingDeskPlaceholder(
  message = "交易台页面已打开，正在读取最近一次服务器快照。"
): AiTradingDeskSnapshot {
  return {
    generatedAt: new Date().toISOString(),
    lastSyncedAt: null,
    mode: "BITGET_DEMO",
    ledgerSource: "BITGET_DEMO",
    ledgerNotice: "会员端只展示服务器保存的Bitget Demo只读快照。",
    strategyEnabled: false,
    mirrorEnabled: false,
    executionConfigured: false,
    executionAllowed: false,
    serverHealthy: false,
    syncStatus: "PARTIAL",
    syncMessage: message,
    operationalState: "CONNECTING",
    operationalStateLabel: "正在读取",
    quoteReady: false,
    latestQuoteAt: null,
    experiment: {
      status: "DISABLED",
      startedAt: null,
      endsAt: null,
      initialEquityUsdt: null,
      currentEquityUsdt: null,
      pnlUsdt: null,
      pnlPct: null,
      maxDrawdownUsdt: null,
      maxDrawdownPct: null,
      dailyPnlUsdt: null,
      dailyPnlPct: null,
      dailyHistory: [],
      stopReason: "",
      securityMessage: "",
    },
    runtime: {
      paused: false,
      pauseReason: "",
      lastHeartbeatAt: null,
      lastStrategyAt: null,
      lastReconcileAt: null,
      heartbeatAgeSeconds: null,
      quoteAgeSeconds: null,
      decisionStatsToday: {
        scanRuns: 0,
        symbolsEvaluated: 0,
        confidenceBlocked: 0,
        alignmentBlocked: 0,
        triggerWaiting: 0,
        riskBlocked: 0,
        marketErrors: 0,
        orderAttempts: 0,
        executed: 0,
      },
    },
    settings: {
      enabled: true,
      showCurrentPositions: true,
      showTradeHistory: true,
      showAbsolutePnl: false,
      historyLimit: 20,
      updatedAt: new Date(0).toISOString(),
    },
    strategies: [],
    planSummary: {
      publishedToday: 0,
      watching: 0,
      armed: 0,
      submittedOrOpen: 0,
      closedToday: 0,
    },
    intentDecisions: [],
    marketQuotes: [],
    publishedPlans: [],
    plans: [],
    positions: [],
    recentTrades: [],
    stats: {
      closedTrades: 0,
      wins: 0,
      losses: 0,
      winRatePct: null,
      averageReturnPct: null,
      bestReturnPct: null,
      worstReturnPct: null,
      tradeCurveMaxDrawdownPct: null,
      netProfitUsdt: null,
    },
  };
}
